### ISSUE TITLE
v1.14

### ISSUE THREAD

**Issue by pietrygamat** [SteveOswald/mod_sslcrl#1]
Is there a chance to update this VS centric project to recently released v1.14 version of Pascal Buchbinder's original mod, yet retaining the Windows compatibility it offers?

**Comment by SteveOswald** [comment]
Hi JockX,

you just can copy the new code into the project and comment out the "APR_DECLARE_OPTIONAL_FN(int, ssl_engine_set, (conn_rec *, ap_conf_vector_t *, int proxy, int enable));" line. Anything should work as expected. My plan is to no longer use the codebase of Pascal, but rewrite the code myself.

Best regards,
Steve
